services:
  fcp-entra-example:
    profiles:
      - app
    build:
      context: .
      target: development
    image: fcp-entra-example
    container_name: fcp-entra-example
    ports:
      - "3001:3001"
      - "9230:9229"
    volumes:
      - ./src:/home/node/src
      - ./package.json:/home/node/package.json
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
    networks:
      - fcp-entra-example
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    command: redis-server --dir /data --save 5 1
    networks:
      - fcp-entra-example
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

networks:
  fcp-entra-example:
    name: fcp-entra-example
    driver: bridge

volumes:
  redis_data:

