# This override file should be used when running automated tests so
# that test output is saved to the host

services:
  fcp-entra-example:
    build:
      target: development
    image: fcp-entra-example-development
    container_name: fcp-entra-example-test
    command: npm run test
    volumes:
      - ./src:/home/node/src
      - ./test:/home/node/test
      - ./test-output:/home/node/test-output
      - ./jest.config.js:/home/node/jest.config.js
      - ./package.json:/home/node/package.json
    environment:
      NODE_OPTIONS: "$NODE_OPTIONS --experimental-vm-modules"
      NODE_ENV: test
      ENTRA_WELL_KNOWN_URL: https://login.microsoftonline.com/${ENTRA_TENANT_ID}/v2.0/.well-known/openid-configuration
      ENTRA_CLIENT_ID: test-client-id
      ENTRA_CLIENT_SECRET: test-client-secret
