sonar.projectKey=DEFRA_fcp-entra-example
sonar.organization=defra

sonar.links.homepage=https://github.com/DEFRA/fcp-entra-example
sonar.links.ci=https://github.com/DEFRA/fcp-entra-example/actions
sonar.links.scm=https://github.com/DEFRA/fcp-entra-example
sonar.links.issue=https://github.com/DEFRA/fcp-entra-example/issues

sonar.sources=src/
sonar.exclusions=test/**/*.test.js
sonar.tests=test/

sonar.javascript.lcov.reportPaths=./coverage/lcov.info

sonar.cpd.exclusions=test/

sonar.coverage.exclusions=src/assets/**
